#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export RBENV_ROOT=/usr/local/share/rbenv


if [ -d "$HOME/.pyenv" ]; then
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi

if [ -d "/usr/local/share/rbenv" ]; then
    export PATH="$RBENV_ROOT/bin:$PATH"
    eval "$(rbenv init -)"
    
    source $RBENV_ROOT/completions/rbenv.zsh
fi

if [ -d "/usr/lib/oracle/12.1/client64" ]; then
    export ORACLE_HOME=/usr/lib/oracle/12.1/client64
    export LD_LIBRARY_PATH=$ORACLE_HOME/lib
fi

if [ -d "/usr/local/share/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin" ]; then
    export PATH="/usr/local/share/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin:$PATH"
    export CCPREFIX=/usr/local/share/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-
    export MODULES_TEMP=~/modules
fi

# Customize to your needs...
export TERM='screen-256color'
[[ $TMUX = "" ]] && export TERM="xterm-256color"
