#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi


## RBENV stuff ##
if [ -d "/usr/local/share/rbenv" ]; then
    export RBENV_ROOT=/usr/local/share/rbenv
fi

if [ -d "~/.rbenv" ]; then
    export RBENV_ROOT=~/.rbenv
fi

if [ -d "$RBENV_ROOT" ]; then
    export PATH="$RBENV_ROOT/bin:$PATH"
    eval "$(rbenv init -)"
fi

# for cyan building ?
if [ -d "$HOME/bin" ]; then
    export PATH="$PATH:$HOME/bin"
fi

if [ -d "~/.rbenv/completions" ]; then
    source ~/.rbenv/completions/rbenv.zsh
elif [ -d "/usr/local/share/rbenv/completions" ]; then
    source /usr/local/share/rbenv/completions
fi


# source /usr/local/share/sqlmap/extra/shutils/completions.zsh

if [ -d "/usr/lib/android-ndk" ]; then
    export PATH=$PATH:/usr/lib/android-ndk
fi

if [ -d "/usr/lib/oracle/12.1/client64" ]; then
    export ORACLE_HOME=/usr/lib/oracle/12.1/client64
    export LD_LIBRARY_PATH=$ORACLE_HOME/lib
fi

if [ -d "/usr/local/share/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin" ]; then
    export PATH="/usr/local/share/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin:$PATH"
    export CCPREFIX=/usr/local/share/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-
    export MODULES_TEMP=~/modules
fi

export PATH=$PATH:/usr/lib/perl5/5.30/core_perl/CORE

# Customize to your needs...
# export TERM='screen-256color'
# [[ -z $TMUX ]] && export TERM="xterm-256color"

# export TERM=rxvt-unicode-256color
export TERM=rxvt-256color


if [ -e "/usr/bin/lsd" ]; then
    alias ls="/usr/bin/lsd"
fi


if [ -d "$HOME/.config/composer/vendor/bin" ]; then
    export PATH="$HOME/.config/composer/vendor/bin:$PATH"
fi


if [ -d "$HOME/.pyenv" ]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi

if [ -e "/usr/bin/wine" ]; then
    export WINEARCH=win32
    export WINEPREFIX=~/.wine32
fi

if [ -e "/usr/share/vulkan/icd.d/nvidia_icd.json" ]; then
    export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json
fi

# if [ -e "/usr/local/share/arnold" ]; then
    # export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/Arnold-6.2.0.1-linux/bin
# On Linux
ARNOLD_ROOT=/opt/Arnold-6.2.0.1-linux
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ARNOLD_ROOT/bin

export ARNOLD_ROOT
export LD_LIBRARY_PATH
# fi

export XDG_CONFIG_HOME=~/.config


export PATH=$PATH:$HOME/.local/bin

typeset -U path
