#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi


## RBENV stuff ##
if [ -d "/usr/local/share/rbenv" ]; then
    export RBENV_ROOT=/usr/local/share/rbenv
fi

if [ -d "~/.rbenv" ]; then
    export RBENV_ROOT=~/.rbenv
fi

if [ -d "$RBENV_ROOT" ]; then
    export PATH="$RBENV_ROOT/bin:$PATH"
    eval "$(rbenv init -)"
fi

# for cyan building ?
if [ -d "$HOME/bin" ]; then
    export PATH="$PATH:$HOME/bin"
fi

if [ -d "~/.rbenv/completions" ]; then
    source ~/.rbenv/completions/rbenv.zsh
elif [ -d "/usr/local/share/rbenv/completions" ]; then
    source /usr/local/share/rbenv/completions
fi



if [ -d "/usr/lib/oracle/12.1/client64" ]; then
    export ORACLE_HOME=/usr/lib/oracle/12.1/client64
    export LD_LIBRARY_PATH=$ORACLE_HOME/lib
fi

if [ -d "/usr/local/share/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin" ]; then
    export PATH="/usr/local/share/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin:$PATH"
    export CCPREFIX=/usr/local/share/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-
    export MODULES_TEMP=~/modules
fi

# Customize to your needs...
# export TERM='screen-256color'
export TERM='tmux-256color'
[[ -z $TMUX ]] && export TERM="xterm-256color"



if [ -d "$HOME/.pyenv" ]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi


