#!/bin/zsh

setopt EXTENDED_GLOB


cd ${ZDOTDIR:-$HOME}

if [[ ! -d "${ZDOTDIR:-$HOME}/.zprezto" ]]; then
    git clone --recursive https://github.com/dtrip/prezto.git ${ZDOTDIR:-$HOME}/.zprezto
fi

for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
    ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

